### ISSUE TITLE
android:lStar not found

### ISSUE THREAD

**Issue by joshuakwak** [rodgomesc/vision-camera-face-detector#31]
The error occurs when building a release apk

**Comment by vozaldi** [comment]
Got the same issue.

It only occurs when I ran `./gradlew assembleRelease`. However running `./gradlew bundleRelease` does not output any error.

**Comment by vozaldi** [comment]
Solved my issue by adding `app:` parameter.

Run `./gradlew app:assembleRelease`

[Source: follow this comment](https://github.com/luggit/react-native-config/issues/330#issuecomment-494915023)
