### ISSUE TITLE
[ANDROID] - Execution failed for task ':vision-camera-face-detector:compileDebugJavaWithJavac'

### ISSUE THREAD

**Issue by saadHeisentech** [rodgomesc/vision-camera-face-detector#46]
I am using `react-native-vision-camera` in my project, after installing the latest version `vision-camera-face-detector": "^0.1.8` the build fails even though I have not used any modules of it. 
I am using `react-native": "0.72.4` and have also gone through the [troubleshoot guide](https://react-native-vision-camera.com/docs/guides/troubleshooting).
This is the error I receive `Execution failed for task ':vision-camera-face-detector:compileDebugJavaWithJavac'`
I have also set the android versions 
```javascript 
buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 26
        compileSdkVersion = 33
        targetSdkVersion = 33
    }
}
````
How do I resolve this issue?

**Comment by shashwats-greytip** [comment]
+1

**Comment by creativekdev** [comment]
I have encountered same issue.

    buildToolsVersion = "33.0.0"
    minSdkVersion = 21
    compileSdkVersion = 33
    targetSdkVersion = 33
        
    "react": "18.2.0",
    "react-native": "0.72.6",
    "react-native-reanimated": "^3.5.4",
    "react-native-vision-camera": "^3.3.1",
    "vision-camera-face-detector": "^0.1.8"

**Comment by saadHeisentech** [comment]
I resolved this issue by downgrading the `react-native-vision-camera` version and it looks like this
```javascript
"react-native-vision-camera" : "^2.16.0",
"vision-camera-face-detector": "github:rodgomesc/vision-camera-face-detector#master" 
```

**Comment by saadHeisentech** [comment]
I resolved this issue by downgrading the `react-native-vision-camera` version and it looks like this
```javsscript
    "react-native-vision-camera": "^2.16.0",
    "vision-camera-face-detector": "github:rodgomesc/vision-camera-face-detector#master"
```
But I would like to know how will it be resolved with the latest version

**Comment by creativekdev** [comment]
ERROR  frame-processor/unavailable: Frame Processors are not enabled. See https://react-native-vision-camera.com/docs/guides/troubleshooting, js engine: hermes

It showing this issue after running.

![image](https://github.com/rodgomesc/vision-camera-face-detector/assets/127048539/1051d701-4c46-41a9-8af4-cb9eb54bf59f)

**Comment by saadHeisentech** [comment]
> ERROR frame-processor/unavailable: Frame Processors are not enabled. See https://react-native-vision-camera.com/docs/guides/troubleshooting, js engine: hermes
> 
> It showing this issue after running.
> 
> ![image](https://user-images.githubusercontent.com/127048539/276600196-1051d701-4c46-41a9-8af4-cb9eb54bf59f.png)

You need to install `"react-native-worklets-core": "^0.2.2"` for frame processors to be enabled and your babel.config.js file should look like this
```javascript
module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      'react-native-reanimated/plugin',
      {
        globals: ['__scanFaces'],
      },
    ],
  ],
};
```

**Comment by creativekdev** [comment]
![image](https://github.com/rodgomesc/vision-camera-face-detector/assets/127048539/88285765-b076-4dca-a34e-c2c06d2a724f)
It's the same, I have tried it right now.
