### ISSUE TITLE
Android ReferenceError: Property '__scanFaces' doesn't exist, js engine: hermes

### ISSUE THREAD

**Issue by inpendio** [rodgomesc/vision-camera-face-detector#5]
Hi, trying out your lib. and getting the above error. __scanFaces is not found in global scope.
Several errors pop up:
`ReferenceError: Property '__scanFaces' doesn't exist, js engine: hermes`
`Error: Requiring module "node_modules/vision-camera-face-detector/src/index.ts", which threw an exception: ReferenceError: Property '__scanFaces' doesn't exist, js engine: hermes`

Env:
```
"react": "17.0.2",
"react-native": "0.66.0",
"react-native-vision-camera": "^2.9.3",
"vision-camera-face-detector": "^0.1.8",
"react-native-reanimated": "^2.3.0-beta.2",
// hermes: true
```
Tested on 2 real devices.

**Comment by iAmGhost** [comment]
Did you set babel plugin correctly? see [guide](https://mrousavy.com/react-native-vision-camera/docs/guides/frame-processors-plugins-final) but you have to add `__scanFaces`.

**Comment by rodgomesc** [comment]
closing due inactivity

**Comment by rahulmishra1991** [comment]
@iAmGhost I tried the same guide but still getting "Property '_scanFaces' doesn't exist" issue. Can anyone please help me into this?

```
    "react": "17.0.2",
    "react-native": "0.68.0",
    "react-native-reanimated": "^2.7.0",
    "react-native-vision-camera": "^2.13.2",
    "vision-camera-face-detector": "^0.1.8"
```

**Comment by bilalattari** [comment]
> __scanFaces

Facing same issue

**Comment by rizbud** [comment]
try using this in `package.json`
```
"vision-camera-face-detector": "rodgomesc/vision-camera-face-detector#master"
```
then run `yarn install` or `npm install` again

references [BenHurMartins/react-native-face-detection/package.json](https://github.com/BenHurMartins/react-native-face-detection/blob/593a2133688eea9c335b5b574a4adfc93f92fc19/package.json)

**Comment by AjayParambath** [comment]
I am also facing the same issue
babel.config :
![image](https://user-images.githubusercontent.com/43914353/168057509-6477356a-b448-43da-98a4-624ef5267b1e.png)

My import 
![image](https://user-images.githubusercontent.com/43914353/168057983-fac727b9-c45a-48d3-8290-bf36c4977770.png)
![image](https://user-images.githubusercontent.com/43914353/168058137-47dee114-6d87-4b95-b29d-b2515ffcbe45.png)


error on metro
![image](https://user-images.githubusercontent.com/43914353/168059600-c285824d-6164-45f6-af9e-2fc6b85557ef.png)

**Comment by AjayParambath** [comment]
> try using this in `package.json`
> 
> ```
> "vision-camera-face-detector": "rodgomesc/vision-camera-face-detector#master"
> ```
> 
> then run `yarn install` or `npm install` again
> 
> references [BenHurMartins/react-native-face-detection/package.json](https://github.com/BenHurMartins/react-native-face-detection/blob/593a2133688eea9c335b5b574a4adfc93f92fc19/package.json)


I tried like you have quoted :
package,json file:
![image](https://user-images.githubusercontent.com/43914353/168064268-8215039f-42d0-4e07-8aae-7f64c89b3764.png)

I got this error :

none of the files were detected:
![image](https://user-images.githubusercontent.com/43914353/168064384-4fe41cb3-d1ae-42f3-9cda-4f0d3b6121db.png)

**Comment by wilav-dev** [comment]
Same issue, any idea? Already added __scanFaces to babel file

**Comment by iAmGhost** [comment]
I don't have time for investigating but here's some suggestions:

* Check other [Frame Processor Plugins](https://mrousavy.com/react-native-vision-camera/docs/guides/frame-processors-plugins-overview) are working, to see if it's plugin issue or react-native-vision camera itself.
* There's an issue that reports app crashes in release mode, it can be problem is not related with babel.
  https://github.com/mrousavy/react-native-vision-camera/issues/954
* See Android native side log if plugin is registered.
   (from issue above: `Also, please share the initial logs that are logged by VisionCamera to Logcat on app-start, it says "Registering Plugins" or something like that.`)
* Reproducible minimal repository will be helpful.

**Comment by Dhruv2110** [comment]
'import 'react-native-reanimated';'....on top of your index file.

**Comment by enzzoperez** [comment]
> try using this in `package.json`
> 
> ```
> "vision-camera-face-detector": "rodgomesc/vision-camera-face-detector#master"
> ```
> 
> then run `yarn install` or `npm install` again
> 
> references [BenHurMartins/react-native-face-detection/package.json](https://github.com/BenHurMartins/react-native-face-detection/blob/593a2133688eea9c335b5b574a4adfc93f92fc19/package.json)

this worked for me
I was try to add the reanimated import in my index.js file (didnt work), I could delete that line after installing from github repo
